### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bruno-rodrigues**
Add pt_BR translation

### CODE REVIEW

**Comment by ankitpokhrel** [comment]
Thanks! Is this Portuguese Brazilian language?

**Comment by bruno-rodrigues** [comment]
Yes.

**Comment by bruno-rodrigues** [comment]
When will this update be available on `wordpress.org`?

**Comment by ankitpokhrel** [comment]
New version will be available by next weekend. You can use the files from master branch till then.

Thanks again!

**Comment by bruno-rodrigues** [comment]
Great. Thank you!

**Pull request merged**
